#ifndef TEXT_ANALYZER_HPP
#define TEXT_ANALYZER_HPP

#include <string>
#include <vector>
#include <string_view>
#include <unordered_map>

class TextAnalyzer {
public:
    // Explicit constructor taking the tokens generated by DocumentParser
    explicit TextAnalyzer(std::vector<std::string_view> tokens);

    // Computes the frequency and TF-IDF weights for each unique word
    void calculate_frequencies();

    // Retrieves the top "N" key concepts sorted by statistical importance
    [[nodiscard]] std::vector<std::pair<std::string, double>> get_top_concepts(size_t top_n) const;

private:
    std::vector<std::string_view> m_tokens;
    
    // Maps a unique word to its raw occurrence count: [Word] -> [Count]
    std::unordered_map<std::string, size_t> m_term_counts;
    
    // Maps a unique word to its computed TF-IDF score: [Word] -> [Score]
    std::unordered_map<std::string, double> m_tfidf_scores;
};

#endif // TEXT_ANALYZER_HPP